title: David's Blog
description: >- # this means to ignore newlines until "baseurl:"
  A quiet corner for random thoughts on tech.
url: "https://daschiller.github.io"
github_username:  daschiller

# Build settings
theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
